# -*- coding: utf-8 -*-
"""Lista_01_go_202403083_Luis_Nunes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152yaGmT-Rn9Bg4DOaPAJ7BPnJC5PTZnG

**Questão 01**

package main

import "fmt"

func main() {
    var n1, n2, n3, media float64

    fmt.Print("Nota 1: ")
    fmt.Scanln(&n1)

    fmt.Print("Nota 2: ")
    fmt.Scanln(&n2)

    fmt.Print("Nota 3: ")
    fmt.Scanln(&n3)

    media = (n1 + n2 + n3) / 3

    fmt.Printf("Média = %.1f\n", media)

    if media > 6.0 {
        fmt.Println("APROVADO")
    } else {
        fmt.Println("REPROVADO")
    }
}

**Questão 02**

package main

import "fmt"

func main() {
    var en, nj, ing, vt, pp, pg, pa, pc float64

    fmt.Print("Número de jogos: ")
    fmt.Scanln(&nj)

    en = 0
    for en < nj {
        fmt.Print("Quantidade de ingressos: ")
        fmt.Scanln(&ing)

        fmt.Print("Número popular: ")
        fmt.Scanln(&pp)

        fmt.Print("Número geral: ")
        fmt.Scanln(&pg)

        fmt.Print("Número arquibancada: ")
        fmt.Scanln(&pa)

        fmt.Print("Número cadeiras: ")
        fmt.Scanln(&pc)

        vt = float64(ing*pp/100*1 + ing*pg/100*5 + ing*pa/100*10 + ing*pc/100*20)

        fmt.Printf("A RENDA DO JOGO N%.f É = %.2f\n",en+1, vt)

        en = en + 1
    }
}

**Questão 03**

package main

import "fmt"

func main() {
    var n1, n2, n3, r, c int

    fmt.Print("Número 1: ")
    fmt.Scanln(&n1)

    fmt.Print("Número 2: ")
    fmt.Scanln(&n2)

    fmt.Print("Número 3: ")
    fmt.Scanln(&n3)

    c = n1*100 + n2*10 + n3
    r = c * c

    if (n1 > 9) || (n2 > 9) || (n3 > 9) || (r < 100) {
        fmt.Println("DÍGITO INVÁLIDO")
    } else {
        fmt.Println(c, ",", r)
    }
}

**Questão 04**

package main

import "fmt"

func main() {
    var kw, d, c, s, kwg float64

    fmt.Print("Salário: ")
    fmt.Scanln(&s)

    fmt.Print("Gasto de kw: ")
    fmt.Scanln(&kwg)

    kw = (s * 0.7) / 100
    c = kw * kwg
    d = c - (c * 0.1)

    fmt.Printf("Custo por kw: R$%.2f\n", kw)
    fmt.Printf("Custo de consumo: R$%.2f\n", c)
    fmt.Printf("Custo com desconto: R$%.2f\n", d)
}

**Questão 05**

package main

import "fmt"

func main() {
    var co, g, v float64
    var tc string

    fmt.Print("Informe o número da conta: ")
    fmt.Scanln(&co)

    fmt.Print("Informe a quantidade de gasto: ")
    fmt.Scanln(&g)

    fmt.Print("Tipo da conta: ")
    fmt.Scanln(&tc)

    if tc == "r" {
        v = 5 + g*5/100
    } else if tc == "c" {
        if g <= 80 {
            v = 500
        } else {
            v = 500 + (g-80)*25/100
        }
    } else if tc == "i" {
        if g <= 100 {
            v = 800
        } else {
            v = 800 + (g-100)*4/100
        }
    }

    fmt.Println("CONTA =", co)
    fmt.Printf("VALOR DA CONTA %.2f\n", v)
}

**Questão 06**

package main

import "fmt"

func main() {
    var c, f float64
    var n, i int

    fmt.Print("Número de testes: ")
    fmt.Scanln(&i)

    n = 0
    for n < i {
        fmt.Print("Fahrenheit: ")
        fmt.Scanln(&f)

        c = 5 * (f - 32) / 9

        fmt.Printf("%.2f FAHRENHEIT EQUIVALE A %.2f\n", f, c)

        n = n + 1
    }
}

**Questão 07**

package main

import "fmt"

func main() {
    var f, p int
    var c, mm float64

    fmt.Print("Fahrenheit: ")
    fmt.Scanln(&f)

    fmt.Print("Polegadas: ")
    fmt.Scanln(&p)

    c = 5 * (float64(f) - 32) / 9
    mm = float64(p) * 25.4

    fmt.Printf("O VALOR EM CELSIUS = %.2f\n", c)
    fmt.Printf("A QUANTIDADE DE CHUVA = %.2f mm\n", mm)
}

**Questão 08**

package main

import "fmt"

func main() {
    var r, h, a, vc float64

    fmt.Print("Raio: ")
    fmt.Scanln(&r)

    fmt.Print("Altura: ")
    fmt.Scanln(&h)

    a = 2*(3.14159*r*r) + 2*3.14159*r*h
    vc = a * 100

    fmt.Printf("O VALOR DO CUSTO = %.2f\n", vc)
}

**Questão 09**

package main

import "fmt"


func main() {
	var a, b, c int
	var d float64

	fmt.Print("Número a: ")
	fmt.Scanln(&a)

	fmt.Print("Número b: ")
	fmt.Scanln(&b)

	fmt.Print("Número c: ")
	fmt.Scanln(&c)

	d = float64((b*b) - 4*a*c)

	fmt.Printf("O VALOR DE DELTA = %.2f\n", d)
}

**Questão 10**

package main

import "fmt"

func main() {
    var a, b, c, d, m1, m2, det float64

    fmt.Print("Número a: ")
    fmt.Scanln(&a)

    fmt.Print("Número b: ")
    fmt.Scanln(&b)

    fmt.Print("Número c: ")
    fmt.Scanln(&c)

    fmt.Print("Número d: ")
    fmt.Scanln(&d)

    m1 = a * d
    m2 = b * c
    det = m1 - m2

    fmt.Printf("O VALOR DO DETERMINANTE É = %.2f\n", det)
}

**Questão 11**

package main

import "fmt"

func main() {
    var n int

    fmt.Print("Insira seu número: ")
    fmt.Scanln(&n)

    if n%3 == 0 && n%5 == 0 {
        fmt.Println("NÚMERO É DIVISÍVEL")
    } else {
        fmt.Println("NÚMERO NÃO É DIVISÍVEL")
    }
}

**Questão 12**

package main

import "fmt"

func main() {
    var h, v float64

    fmt.Print("O número de horas : ")

    fmt.Scanln(&h)

    if h >= 3 {
        v = 10.0 * (h / 3)
    } else {
        v = 5.0 * h
    }

    fmt.Printf("O VALOR A PAGAR É = %.2f\n", v)
}

**Questão 13**

package main

import "fmt"

func main() {
    var n float64
    var con string

    fmt.Print("Nota: ")
    fmt.Scanln(&n)

    if n < 0 || n > 10.0 {
        fmt.Println("DIGITO INVALIDO")
    } else {
        if n <= 5.9 {
            con = "d"
        } else if n >= 6.0 && n < 7.4 {
            con = "c"
        } else if n >= 7.5 && n < 8.9 {
            con = "b"
        } else if n >= 9.0 {
            con = "a"
        }

        fmt.Printf("NOTA = %.1f CONCEITO = %s\n", n, con)
    }
}

**Questão 14**

package main

import (
    "fmt"
    "math"
)

func main() {
    var h, ar, v float64

    fmt.Print("Altura: ")
    fmt.Scanln(&h)

    fmt.Print("Aresta: ")
    fmt.Scanln(&ar)

    v = (1.0 / 3.0) * ((3.0 * math.Pow(ar, 2) * math.Sqrt(3)) / 2.0) * h

    fmt.Printf("O VOLUME DA PIRÂMIDE É = %.2f METROS CÚBICOS\n", v)
}

**Questão 15**

package main

import "fmt"

func main() {
	var n, i int
	var q float64

	fmt.Print("Digite um valor inteiro N (5 < N < 2000): ")
	fmt.Scanln(&n)

	for i = 2; i <= n; i += 2 {
		q = float64(i * i)
		fmt.Printf("%d^2 = %.0f\n", i, q)
	}
}

**Questão 16**

package main

import "fmt"

func main() {
    var s, sr float64

    fmt.Print("Salário: ")
    fmt.Scanln(&s)

    if s <= 300 {
        sr = s + (s * 50 / 100)
    } else {
        sr = s + (s * 30 / 100)
    }

    fmt.Printf("SALÁRIO COM REAJUSTE = %.2f\n", sr)
}

**Questão 17**

package main

import "fmt"

func main() {
	var pr, p, s, n int

	fmt.Println("Insira dois números:")
	fmt.Scanln(&p, &s)

	if p%2 == 0 {
		for n = 1; n <= s; n++ {
			pr = p + (n - 1) * 2
			fmt.Printf("%d ", pr)
		}
	} else {
		fmt.Println("O PRIMEIRO NÚMERO NÃO É PAR")
	}
}

**Questão 18**

package main

import "fmt"

func main() {
	var vi, r, ne, s, n int

	fmt.Println("Insira o valor inicial, a razão e o número de elementos:")
	fmt.Scanln(&vi, &r, &ne)

	s = 0

	for n = 0; n <= ne-1; n++ {
		s += vi + n*r
	}

	fmt.Print(s, " ")
}

**Questão 19**

package main

import "fmt"

func main() {
    var n, k int
    var s float64

    fmt.Print("Numero: ")
    fmt.Scanln(&n)

    if n < 1 {
        fmt.Println("Número inválido!")
    } else {
        s = 0
        for k = 1; k <= n; k++ {
            s += 1.0 / float64(k)
        }
        fmt.Printf("Resultado = %.6f\n", s)
    }
}

**Questão 20**

package main

import "fmt"

func main() {
    var h, m, s, tts int

    fmt.Print("Horas: ")
    fmt.Scanln(&h)

    fmt.Print("Minutos: ")
    fmt.Scanln(&m)

    fmt.Print("Segundos: ")
    fmt.Scanln(&s)

    tts = h*3600 + m*60 + s

    fmt.Println("O TEMPO EM SEGUNDOS É =", tts)
}
"""