# -*- coding: utf-8 -*-
"""Lista_01_202403083_Luis_Nunes_ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18eId6wtvZqISERWXsFvyY6cIo-6iVNMo

**Questão 1**

Algoritmo "semnome"

Var

n1, n2, n3, media: real


Inicio

escreva ("Nota 1: ")

leia (n1)

escreva ("Nota 1: ")

leia (n2)

escreva ("Nota 3: ")

leia (N3)

media <- (n1 + n2 + n3)/3

escreval ("Media =", media:1:1)

se (media > 6.00) entao

escreva ("APROVADO")

senao

escreva ("REPROVADO")

fimse

Fimalgoritmo

**Questão 2**

Algoritmo "semnome"

Var

en, nj, ing: inteiro

vt, pp, pg, pa, pc: real


Inicio

escreva ("Numero de jogos: ")

leia (nj)

en <- 0

enquanto (en < nj) faca

escreva ("Quantidade de ingressos: ")

leia (ing)

escreva ("Numero popular: ")

leia (pp)

escreva ("Numero geral: ")

leia (pg)

escreva ("Numero arquibancada: ")

leia (pa)

escreva ("Numero cadeiras: ")

leia (pc)

vt <- (ing * pp/100 * 1 + ing * pg/100 * 5 + ing * pa/100 * 10 + ing * pc/100 * 20)

escreva ("A RENDA DO JOGO N", en + 1, " E =", vt)

en <- (en + 1)

fimenquanto

**Questão 3**

Algoritmo "semnome"

Var
n1, n2, n3, r, c: inteiro

Inicio

escreva ("Numero 1: ")

leia (n1)

escreva ("Numero 2: ")

leia (n2)

escreva ("Numero 3: ")

leia (n3)

c <- (n1 * 100 + n2 * 10 + n3)

r <- (c * c)

se (c < 100) ou (r < 100) entao

escreval ("DIGITO INVALIDO")

senao

escreva (c, ",", r)

fimse

Fimalgoritmo

**Questão 4**

Algoritmo "semnome"

Var
kw, d, c, s, kwg: real

Inicio

escreva ("Salario: ")

leia (s)

escreva ("Gasto de kw: ")

leia (kwg)

kw <- (s * 0.7)/100

c <- (kw * kwg)

d <- (c - c * 0.1)

escreval ("Custo por kw: R$:", kw:6:2)

escreval ("Custo de consumo: R$:", c:6:2)

escreval ("Custo com desconto R$:", d:6:2)

Fimalgoritmo

**Questão 5**


Var
c, g, v: real

tc: caracter

Inicio

escreva ("Informe o numero da conta: ")

leia (c)

escreva ( "Informe a quantidade de gasto: ")

leia (g)

escreva ("Tipo da conta: ")

leia (tc)

se (tc = "r") entao

v <- (5 + g * 5/100)

fimse

se (tc = "c") entao

se(g <= 80) entao

v <- (500)

senao

v <- (500 + (g - 80) * 25/100)

fimse

fimse

se (tc = "i") entao

se(g <= 100) entao

v <- (800)

senao

v <- (800 + (g - 100) * 4/100)

fimse

fimse

escreval ("CONTA =", c)

escreval ("VALOR DA CONTA", v:8:2)

Fimalgoritmo

**Questão 6**

Algoritmo "semnome"

Var

c, f, m: real

n, i: inteiro

Inicio

escreva ("Numero de testes: ")

leia (i)

enquanto (n < i) faca

escreva ("Fahrenheit: ")

leia (f)

c <- 5 * (f - 32)/9

escreval (f:6:2," FAHRENHEIT EQUIVALE A ", c:6:2)

n <- (n + 1)

fimenquanto

Fimalgoritmo

**Questão 7**

Algoritmo "semnome"

Var

f, p: inteiro

c, mm: real

Inicio

escreva ("Fahrenhei: ")

leia (f)

escreva ("Polegadas: ")

leia (p)

C <- (5 * (f - 32)/9)

mm <- (p * 25.4)

escreval ("O VALOR EM CELSIUS =", c:8:2)

escreval ("A QUANTIDADE DE CHUVA E =", mm:8:2)

Fimalgoritmo

**Questão 8**

Algoritmo "semnome"

Var

r, h, a, vc: real

Inicio

escreva ("Raio: ")

leia (r)

escreva ("Altura: ")

leia (h)

a <- (2 *(3.14159 * r ^ 2)) + (2 * 3.14159 * r * h)

vc <- (a * 100)

escreva ("O VALOR DO CUSTO E =", vc:6:2)

Fimalgoritmo

**Questão 9**

Algoritmo "semnome"

Var

a, b, c: inteiro

d: real


Inicio

escreva ("numero a: ")

leia (a)

escreva ("numero b: ")

leia (b)

escreva ("numero c: ")

leia (c)

d <- ((b ^ 2) - 4 * a * C))

escreva ("O VALOR DE DELTA E =", d:8:2)

Fimalgoritmo

**Questão 10**
Algoritmo "semnome"

Var

a, b, c, d, m1, m2, det: real

Inicio

escreva ("Numero a: ")

leia (a)

escreva ("Numero b: ")

leia (b)

escreva ("Numero c: ")

leia (c)

escreva ("Numero d: ")

leia (d)

m1 <- (a * d)

m2 <- (b * c)

det <- (m1 - m2)

escreva ("O VALOR DO DETERMINANTE E =", det:8:2)


Fimalgoritmo

**Questão 11**

Algoritmo "semnome"

Var

n: inteiro

Inicio

escreva ("Insira seu numero: ")

leia (n)

se (n % 3 = 0) e (n % 5 = 0) entao

escreva ("NUMERO E DIVISIVEL")

senao

escreva ("NUMERO NAO E DIVISIVEL")

fimse


Fimalgoritmo

**Questão 12**

Algoritmo "semnome"

Var

nh, vp: real

Inicio

escreva ("Horas de uso: ")

leia (nh)

se (nh < 3) entao

vp <- (nh * 5)

senao

vp <- (nh/3 * 10) + ((nh % 3) * 5)

fimse

escreva ("O VALOR A PAGAR E =", vp:8:2)

Fimalgoritmo

**Quesão 13**

Algoritmo "semnome"

Var

n: real

con: caracter

Inicio

escreva ("Nota: ")

leia (n)

se (n < 0) ou (N > 10.0) entao

escreval ("DIGITO INVALIDO")

senao

se (n <= 5.9) entao

con <- ("d")

fimse

se (n >= 6.0) e ( n < 7.4) entao

con <- ("c")

fimse

se (n >= 7.5) e (n < 8.9) entao

con <- ("b")

fimse

se (n >= 9.0) entao

con <- ("a")

fimse

fimse

se (n < 0) ou (N > 10.0) entao

Fimalgoritmo

senao

escreval ("NOTA = ", n:2:1, " CONCEITO = ", con)

fimse

Fimalgoritmo

**Questão 14**

Algoritmo "semnome"

Var

h, ar, v: real

Inicio

escreva ("Altura: ")

leia (h)

escreva ("Aresta: ")

leia (ar)

v <- (1/3 * ((3 * ar^2 * raizq(3))/2)) * (h)

escreva ("O VOLUME DA PIRAMIDE E =", v:8:2, "  METROS CUBICOS")


Fimalgoritmo

**Questão 15**

Algoritmo "semnome"

Var

n, i: inteiro

q: real

inicio

Escreva("Digite um valor inteiro N (5 < N < 2000): ")

Leia(N)

para i de 2 ate N passo 2 faca

q <- i ^ 2

Escreval(i, "ˆ2 = ", q)

fimPara

Fimalgoritmo

**QUESTÃO 16**

Algoritmo "semnome"

Var

s, sr: real

Inicio

escreva ("Salario: ")

leia (s)

se (s <= 300) entao

sr <- (s + (s * 50/100))

senao

sr <- (s + (s * 30/100))

fimse

escreva ("SALARIO COM REAJUSTE = ", sr:9:2)


Fimalgoritmo

**QUESTÃO 17**

Algoritmo "semnome"

Var

pr, p, s, n: inteiro

Inicio

escreval ("Insira dois numeros :")

leia (p, s)

se (p % 2 = 0) entao

para n de 1 ate s faca

pr <- (p + (n - 1) * 2)

escreva (pr, " ")

fimpara

senao

escreva ("O PRIMEIRO NUMERO NAO E PAR")

fimse

Fimalgoritmo

**QUESTÃO 18**

Algoritmo "semnome"

Var

vi, r, ne, s, n: inteiro

Inicio

escreval ("insira o valor inicial, a razao, e o numero de elementos: ")

leia (vi, r, ne)

s <- 0

para n de 0 ate ne - 1 faca

s <- (s + (vi + n * r))

fimpara

escreva (s, " ")

Fimalgoritmo

**QUESTÃO 19**

Algoritmo "semnome"

Var

n, k: inteiro

s: real

Inicio

escreva("Numero: ")

leia (n)

se (n < 1) entao

escreva ("Numero invalido!")

senao

s <- 0

para k de 1 ate n faca

s <- (s + 1/k)

fimpara

fimse

escreva ("reultado = ", s:9:6)


Fimalgoritmo

**QUESTÃO 20**

Algoritmo "semnome"

Var

h, m, s, tts: inteiro


Inicio

escreva ("Horas: ")

leia (h)

escreva ("Minutos: ")

leia (m)

escreva ("Segundos: ")

leia (s)

tts <- (h * 3600 + m * 60 + s)

escreva ("O TEMPO EM SEGUNDOS E =", tts)

Fimalgoritmo
"""